### ISSUE TITLE
Update pip version

### ISSUE THREAD

**Issue by D3f0** [ClusterHQ/machinist#39]
Pip version does not work it fails to import:
```
In [1]: import machinist
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-786a8cf3703c> in <module>()
----> 1 import machinist

/home/nahuel/.virtualenvs/foo/lib/python2.7/site-packages/machinist/__init__.py in <module>()
    115     ]
    116 
--> 117 from ._fsm import (
    118     IFiniteStateMachine, IOutputExecutor, IRichInput,
    119     StateMachineDefinitionError, ExtraTransitionState,

/home/nahuel/.virtualenvs/foo/lib/python2.7/site-packages/machinist/_fsm.py in <module>()
     46     [FSM_TERMINAL_STATE],
     47     [],
---> 48     u"A finite state machine was initialized.")
     49 
     50 LOG_FSM_TRANSITION = ActionType(
```

Installed as editable with pip and it works fine.

**Comment by exarkun** [comment]
Hi.  Thanks for your interest in machinist.  I think you're saying that the version of machinist on PyPI doesn't currently work when installed with the newest version of eliot.  If so, this has been fixed in master@HEAD already - it just needs to be released.

If you think the problem you encountered is something else, feel free to re-open the issue with more details.

**Comment by itamarst** [comment]
0.2.0 is now up on PyPI, so you should be able to just `pip install machinist` and it'll work.

**Comment by D3f0** [comment]
Thank you guys!
